apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
spec:
  service:
    ports:
      - name: example
        port: 12000
        targetPort: 12000
      - name: example-without-api-credentials
        port: 13000
        targetPort: 13000
  github:
    example:
      repositories:
        - owner: muhametkaqandolli
          names:
            - argo-events
            - argo-workflows
      webhook:
        endpoint: /push
        port: "12000"
        method: POST
        url: http://events-webhook.ops-test.healios.care/
      events:
        - "*"

      # apiToken refers to K8s secret that stores the github api token
      # if apiToken is provided controller will create webhook on GitHub repo
      # +optional
      apiToken:
        # Name of the K8s secret that contains the access token
        name: mk-github-access
        # Key within the K8s secret whose corresponding value (must be base64 encoded) is access token
        key: token

#      # webhookSecret refers to K8s secret that stores the github hook secret
#      # +optional
#      webhookSecret:
#        # Name of the K8s secret that contains the hook secret
#        name: github-access
#        # Key within the K8s secret whose corresponding value (must be base64 encoded) is hook secret
#        key: secret

      # type of the connection between event-source and Github.
      # You should set it to false to avoid man-in-the-middle and other attacks.
      insecure: true
      # Determines if notifications are sent when the webhook is triggered
      active: true
      # The media type used to serialize the payloads
      contentType: json
      
    example-without-api-credentials:
      owner: "muhametkaqandolli"
      repository: "argo-apps"
      webhook:
        endpoint: "/push"
        port: "13000"
        method: "POST"
      events:
        - "*"
      webhookSecret:
        name: events-webhook-certs
        key: secret
      insecure: true
      active: true
      contentType: "json"

#    example-with-secure-connection:
#      owner: "argoproj"
#      repository: "argo"
#      webhook:
#        endpoint: "/push"
#        port: "13000"
#        method: "POST"
#        url: "http://myargofakeurl.fake"
#        # k8s secret that contains the cert
#        serverCertSecret:
#          name: my-secret
#          key: cert-key
#        # k8s secret that contains the private key
#        serverKeySecret:
#          name: my-secret
#          key: pk-key
#      events:
#        - "push"
#        - "delete"
#      apiToken:
#        name: github-access
#        key: token
#      webhookSecret:
#        name: github-access
#        key: secret
#      insecure: true
#      active: true
#      contentType: "json"

###### Short version
# apiVersion: argoproj.io/v1alpha1
# kind: EventSource
# metadata:
#   name: github
#   namespace: argocd
# spec:
#   service:
#     ports:
#       - name: example
#         port: 12000
#         targetPort: 12000
#   github:
#     example:
#       id: 0
#       webhook:
#         endpoint: /push
#         method: POST
#         port: '12000'
#         url: http://events-webhook.ops-test.healios.care/
#       owner: 'muhametkaqandolli'
#       repository: 'argo-apps'
#       events:
#         - '*'
#       apiToken:
#         name: mk-github-access
#         key: token
#       insecure: true
#       active: true
#       contentType: json
#       repositories:
#         - owner: muhametkaqandolli
#           names:
#             - argo-apps

