apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webapp-sample
spec:
  template:
    serviceAccountName: ops-test-sensor-sa
  dependencies:
  - name: push
    eventSourceName: github
    eventName: argo-app
  triggers:
  - template:
      name: webapp-sample
      k8s:
        operation: create
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Application
            metadata:
              name: demo-webapp
              namespace: nexus-ops-test
            spec:
              project: default
              source:
                repoURL: 'https://github.com/muhametkaqandolli/argo-apps.git'
                targetRevision: "HEAD"
                path: "web-service"
              destination:
                namespace: nexus-ops-test
                server: 'https://kubernetes.default.svc'
              syncPolicy:
                automated: {}