apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: dotnetweb-github-sensor
spec:
  template:
    serviceAccountName: ops-test-sensor-sa
  dependencies:
    - name: push
      eventSourceName: github
      eventName: dotnetweb
  triggers:
    - template:
        name: dotnetweb-workflow-trigger
        argoWorkflow:
          # operation: submit
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: dotnet-webapp-image-
              spec:
                entrypoint: main
                workflowTemplateRef:
                  name: dotnet-webapp-image