apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: github-sensor
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: github
      eventName: argo-app
  triggers:
    - template:
        name: webhook-deployment-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                generateName: hello-world-
              spec:
                replicas: 1
                selector:
                  matchLabels:
                    app: mydeploy
                template:
                  metadata:
                    labels:
                      app: mydeploy
                  spec:
                    containers:
                      - name: hello-container
                        args:
                          - "hello world"
                        command:
                          - cowsay
                        image: "docker/whalesay:latest"
          parameters:
            - src:
                dependencyName: test-dep
              dest: spec.template.spec.containers.0.args.0         