apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
spec:
  service:
    ports:
      - name: dotnetweb
        port: 13000
        targetPort: 13000
  github:
    dotnetweb:
      repository: dotnet-webapp
      owner: muhametkaqandolli
      webhook:
        endpoint: /dotnetweb
        port: "13000"
        method: POST
        url: https://events-github.ops-test.healios.care
      events:
        - "*"
      apiToken:
        name: mk-github-access
        key: token
      contentType: "json"
      insecure: true
      active: true
