apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: mk-webhook
  namespace: argo
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    mk-example:
      port: "12000"
      endpoint: "/"
      method: POST
