apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: mk-webhook
  namespace: argo
spec:
  service:
    ports:
      - port: 12001
        targetPort: 12001
  webhook:
    mk-example:
      port: "12001"
      endpoint: "/"
      method: POST
# apiVersion: argoproj.io/v1alpha1
# kind: EventSource
# metadata:
#   name: github
#   namespace: argo
# spec:
#   service:
#     ports:
#       - name: example
#         port: 12000
#         targetPort: 12000
#   github:
#     example:
#       webhook:
#         endpoint: /push
#         method: POST
#         port: '12000'
#         url: http://events-webhook.ops-test.healios.care/
#       owner: 'muhametkaqandolli'
#       repository: 'argo-apps'
#       events:
#         - '*'
#       apiToken:
#         name: mk-github-access
#         key: token
#       insecure: true
#       active: true
#       contentType: json
#       repositories:
#         - owner: muhametkaqandolli
#           names:
#             - argo-apps